// Generated by CoffeeScript 1.6.3
var merge;

merge = module.exports = function() {
  var clone, copy, from, i, inverse, name, options, src, target, to, _i;
  target = arguments[0];
  from = 1;
  to = arguments.length;
  if (typeof target === 'boolean') {
    inverse = !!target;
    target = arguments[1];
    from = 2;
  }
  if (typeof target !== "object" && typeof target !== 'function') {
    target = {};
  }
  for (i = _i = from; from <= to ? _i < to : _i > to; i = from <= to ? ++_i : --_i) {
    if ((options = arguments[i]) !== null) {
      for (name in options) {
        src = target[name];
        copy = options[name];
        if (target === copy) {
          continue;
        }
        if ((copy != null) && typeof copy === 'object' && !Array.isArray(copy) && !(copy instanceof RegExp)) {
          clone = src && (src && typeof src === 'object' ? src : {});
          target[name] = merge(false, clone, copy);
        } else if (copy !== void 0) {
          if (!(inverse && typeof target[name] !== 'undefined')) {
            target[name] = copy;
          }
        }
      }
    }
  }
  return target;
};
