// Generated by CoffeeScript 1.6.3
var Interface, unstyle;

unstyle = require('./unstyle');

Interface = require('readline').Interface;

Interface.prototype.setPrompt = (function(parent) {
  return function(prompt, length) {
    var args;
    args = Array.prototype.slice.call(arguments);
    if (!args[1]) {
      args[1] = unstyle(args[0]).length;
    }
    return parent.apply(this, args);
  };
})(Interface.prototype.setPrompt);
